//Import Pages


//Import Global Stylesheet
import './globals.css';

import PocketBase from 'pocketbase';

const pb = new PocketBase('http://127.0.0.1:8090');


// const authData = await pb.admins.authWithpasswor



const websiteLogo = await pb.collection('assets').getList(1, 1, {
  sort: '-created',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icon: websiteLogo,
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <img></img>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
